# Generated by Django 3.1.3 on 2021-01-05 22:33

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import images_upload.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='UserImages',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uploaded_date', models.DateTimeField(blank=True, default=datetime.datetime.now)),
                ('private', models.BooleanField(default=False)),
                ('image', models.ImageField(default='post/default.jpg', upload_to=images_upload.models.upload_to, verbose_name='Image')),
                ('user', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='user', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['id'],
            },
        ),
    ]
